name: Build and Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # Needed to update the k8s manifest

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    # Define these variables globally so all steps can see them
    env:
      ECR_REPOSITORY: link-service
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        working-directory: link-service
        run: mvn clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- STEP 1: BUILD (But don't push yet) ---
      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        working-directory: link-service
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # --- STEP 2: SECURITY SCAN (The Gatekeeper) ---
      - name: Install and Run Trivy
        run : |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v0.57.1
          ./trivy image \
                    --format table \
                    --exit-code 1 \
                    --severity CRITICAL,HIGH \
                    --ignore-unfixed \
                    --vuln-type os,library \
                    ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        

      # --- STEP 3: PUSH (Only runs if Scan passes) ---
      - name: Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        working-directory: link-service
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      # --- STEP 4: DEPLOY (GitOps) ---
      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image: .*|image: ${{ env.IMAGE_URI }}|g" k8s/link-service.yaml
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add k8s/link-service.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push